# This is a config for E2B sandbox template.
# You can use template ID (z1hqhk13howh3sd3vsd8) or template name (vibe-ai-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-ai-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-ai-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-ai-nextjs')

team_id = "6d217b70-c48a-43c1-9fd6-b9d620c938cc"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-ai-nextjs"
template_id = "z1hqhk13howh3sd3vsd8"
